import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";

import { League_Spartan } from "next/font/google";
import "./style/globals.css";
import PageHeader from "./components/header";
import ThemeProvider from "./components/providers";
import { ControlPanelWrapper } from "./style/controlStyle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const leaguespartan = League_Spartan({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={leaguespartan.className}>
        <ThemeProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
